updated all files
francis3400/francis3400.github.io pull request #4
Opened 2022-09-29 19:32 UTC by francis3400

- [ ] updated index files
- [ ] updated style files
- [ ] Created a pull request
- [ ] Corrected all errors.

2022-09-29 20:28 UTC, christianbiring1 requested changes
Hi @francis3400 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![164625215-44f24c98-53c8-49c1-b68f-05723a584dc2](https://user-images.githubusercontent.com/97100091/193135083-9a2cd814-5c54-489f-9ca4-0eb55e368bcf.gif)

## Highlights
- [ ] All linters are green :heavy_check_mark: 
- [ ] Descriptive PR.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 20:28 UTC, christianbiring1 commented on index.html
> +
- [ ] Kindly make sure your social icons are well aligned as you can see :point_down: 
![image](https://user-images.githubusercontent.com/97100091/193131600-44c915f0-407f-4ad6-b74b-f735c9072312.png)

2022-09-29 20:28 UTC, christianbiring1 commented on index.html
> +              </ul>
- [ ] Kindly make sure you stick to the design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/193132439-4b8617e7-0873-4ae7-a697-d38a0de0ba4a.png)
The Figma template :point_down: 
![image](https://user-images.githubusercontent.com/97100091/193132746-436659a8-d804-4a8f-8dde-948cb6a025d7.png)

2022-09-29 20:28 UTC, christianbiring1 commented on index.html
> +         <h3 class="connect">LET’S CONNECT</h3>
- [ ] Kindly make sure you stick to the design. Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/193133564-6071e114-a81b-4fbc-af3d-ec37446eec89.png)
Figma design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/193133751-bdcd0ae4-41f2-4578-915c-534fb6fa77a0.png)

2022-09-29 20:28 UTC, christianbiring1 commented on index.html
> +            <p id="aboutText">
Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/193134281-a5b269f4-5737-4a82-a455-e1223fe26fb8.png)
 Figma design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/193134528-8eb5101f-1ba1-40d2-a9d3-b468dd743f4f.png)

2022-09-30 02:29 UTC, franclobo reviewed
Hi @francis3400, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a professional 👀 README file according with the [README template](https://github.com/microverseinc/readme-template/blob/master/README.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-09-30 03:32 UTC, emmiiorji approved these changes
Hi @francis3400, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congratulations](https://user-images.githubusercontent.com/20554583/193184090-8cb71a79-3908-4853-b4ed-bbd5889b81b0.gif)


## Highlights✔

- You have implemented suggested changes
- Linter checks are passing
- Good commit messages
- Adherence to GitHub flow


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 03:45 UTC, merged